# Numpy 배열의 기초
1. 배열 속성 지정: 배열의 크기, 모양, 메모리 소비량, 데이터 타입 지정
2. 배열 인덱싱: 개별 배열 오솟값을 가져오고 실행
3. 배열 슬라이싱: 큰 배열 내에 있는 작은 하위 배열을 가져오고 실행
4. 배열 재구조화: 해당 배열의 형상을 변경
5. 배열 결합 및 분할: 여러 배열을 하나로 결합하고 하나의 배열을 여러 개로 분할

### 1. NumPy 배열 속성 지정

In [33]:
import numpy as np
np.random.seed(0) 
# seed for reproducibility
# This means that every time you run your code with the same seed,
# you will get the same sequence of random numbers.

x1=np.random.randint(10, size=6)
x2=np.random.randint(10, size=(3,4))
x3=np.random.randint(10, size=(3,4,5), dtype='int64')


cf.
- Random Seed: A seed is an initial value used by the random number generator to start the sequence. By setting the seed, you ensure that the random number generator produces the same sequence of numbers each time.
- Reproducibility: This is useful for debugging, testing, and sharing code, as it allows others to reproduce the same results.

In [34]:
import numpy as np

# Set the seed for reproducibility
np.random.seed(0)

# Generate some random numbers
random_numbers = np.random.rand(3)

print(random_numbers)

[0.5488135  0.71518937 0.60276338]


In [35]:
print("x3 ndim:", x3.ndim) # number of dimensions
print("x3 shape:", x3.shape) # size of each dimension
print("x3 size:", x3.size) # total size of the array

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [36]:
print("dtype:", x3.dtype) # data type of the array

dtype: int64


In [37]:
print("itemsize:", x3.itemsize, "bytes") # size of each element
print("nbytes:", x3.nbytes, "bytes") # total size of array: itemsize x size

itemsize: 8 bytes
nbytes: 480 bytes


2. 배열 인덱싱: 단일 요소에 접근하기
- NumPy인덱싱: 파이썬 표준 인덱싱과 비슷
- [] 안에 원하는 인덱스 지정 (0부터 시작)

In [38]:
print(x1)

[5 0 3 3 7 9]


In [39]:
print(x1[0])

5


In [40]:
print(x1[4])

7


In [41]:
# 음수 인덱싱
print(x1[-1])

9


In [42]:
print(x1[-2])

7


In [43]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [44]:
x2[0,0]

np.int32(3)

In [45]:
x2[2,0]

np.int32(1)

In [46]:
x2[2,-1]

np.int32(7)

In [47]:
# 위 인덱스 표기법을 사용해 값을 수정할 수도 있음
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [48]:
x1[0]=3.14159 # 이 값은 자동으로 변환됨 (소수점 이하가 잘림)
x1

array([3, 0, 3, 3, 7, 9], dtype=int32)

In [32]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

3. 배열 슬라이싱: 하위 배열에 접근하기
- 콜론(:) 기호로 표시되는 슬라이스 표기법으로 하위 배열에 접근할 수 있다
- x[start:stop:step] (defaul= start=0, stop=차원크기, step=1)

In [50]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# 첫 다섯 개 요소
x[:5]

array([0, 1, 2, 3, 4])

In [52]:
# 인덱스 5 다음 요소들
x[5:]

array([5, 6, 7, 8, 9])

In [53]:
# 중간 하위 배열
x[4:7]

array([4, 5, 6])

In [54]:
# 하나 걸러 하나씩의 요소로 구성된 배열
x[::2]

array([0, 2, 4, 6, 8])

In [55]:
# 인덱스 1에서 시작해 하나 걸러 하나씩 요소로 구성된 배열
x[1::2]

array([1, 3, 5, 7, 9])

In [56]:
# step 값이 음수일 때 start 인덱스와 end 인덱스를 생략하면 기본값은 배열의 끝부터 시작
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [57]:
# 인덱스 5부터 하나 걸러 하나씩 요소를 거꾸로 나열
x[5::-2]

array([5, 3, 1])

4. 다차원 하위 배열
- 다차원 슬라이싱도 콤마로 구분된 다중 슬라이스를 사용해 똑같은 방식으로 동작

In [59]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)